-- T_CommodityPriceテーブルの現在の構造を確認

-- カラム一覧を確認
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'T_CommodityPrice'
ORDER BY ORDINAL_POSITION;

-- テーブル名の確認
SELECT 
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%CommodityPrice%'
ORDER BY TABLE_NAME;